version: '3.10'

services:
  django:
    build: .
    command: gunicorn dreamforskin.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/dreamforskin
      - static_data:/dreamforskin/static
    expose:
      - 8000
    env_file:
      - ./.env.dev

  db: 
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dreamforskin_db

  nginx: 
    image: nginx:1.21
    depends_on: 
      - django
    ports: 
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pg_data:
  static_data:
